version: "3.9"

services:
  lucee:
    build:
      context: ./build
      dockerfile: Dockerfile.local
    container_name: cms_condominio
    ports:
      - "10000:10000"
    volumes:
      - ./src:/app
    environment:
      PORT: 10000
      ENVIRONMENT: development
      BOX_SERVER_PROFILE: development
      BOX_SERVER_WEB_REWRITES_ENABLE: "true"
      BOX_SERVER_WEB_DIRECTORY: /app
      BOX_SERVER_WEB_HOST: "0.0.0.0"
      BOX_SERVER_WEB_HTTP_PORT: "10000"
      LUCEE_ADMIN_PASSWORD: ${LUCEE_ADMIN_PASSWORD}
      CFCONFIG_DATASOURCES_CMSCONDOMINIO_CLASSNAME: ${CFCONFIG_DATASOURCES_CMSCONDOMINIO_CLASSNAME}
      CFCONFIG_DATASOURCES_CMSCONDOMINIO_CONNECTIONSTRING: ${CFCONFIG_DATASOURCES_CMSCONDOMINIO_CONNECTIONSTRING}
      CFCONFIG_DATASOURCES_CMSCONDOMINIO_USERNAME: ${CFCONFIG_DATASOURCES_CMSCONDOMINIO_USERNAME}
      CFCONFIG_DATASOURCES_CMSCONDOMINIO_PASSWORD: ${CFCONFIG_DATASOURCES_CMSCONDOMINIO_PASSWORD}
      CFCONFIG_DATASOURCES_CMSCONDOMINIO_BUNDLENAME: ${CFCONFIG_DATASOURCES_CMSCONDOMINIO_BUNDLENAME}
      CFCONFIG_DATASOURCES_CMSCONDOMINIO_HOST: ${CFCONFIG_DATASOURCES_CMSCONDOMINIO_HOST}
      CFCONFIG_DATASOURCES_CMSCONDOMINIO_PORT: ${CFCONFIG_DATASOURCES_CMSCONDOMINIO_PORT}
      CFCONFIG_DATASOURCES_CMSCONDOMINIO_DATABASE: ${CFCONFIG_DATASOURCES_CMSCONDOMINIO_DATABASE}
    tty: true
